---
    # Use command module
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbea$

    # Use command module
  - name: install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

    # Use copy module
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/metricbeat-configuration.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Use command module
  - name: enable and configure Docker module
    command: metricbeat modules enable docker

    # Use command module
  - name: setup metricbeat
    command: metricbeat setup

    # Use comand comdule
  - name: start metricbeat
    command: metricbeat run